export type ArcaTestata = {
  ID: number;
  ESERCIZIO: string;
  ESANNO: string;
  TIPODOC: string;
  NUMERODOC: string;
  DATADOC: string | null;
  CODICECF: string;
  CODCNT: string;
  MAGPARTENZ: string;
  MAGARRIVO: string;
  NUMRIGHEPR: number;
  AGENTE: string;
  AGENTE2: string;
  VALUTA: string;
  PAG: string;
  SCONTI: string;
  SCONTIF: number;
  SCONTOCASS: string;
  SCONTOCASF: number;
  PROVV: string;
  PROVV2: string;
  CAMBIO: number;
  DATADOCFOR: string | null;
  NUMERODOCF: string;
  TIPOMODULO: string;
  LISTINO: string;
  ZONA: string;
  SETTORE: string;
  DESTDIV: string;
  DATACONSEG: string | null;
  TRDATA: string | null;
  TRORA: string;
  PESOLORDO: number;
  PESONETTO: number;
  VOLUME: number;
  VETTORE1: string;
  V1DATA: string | null;
  V1ORA: string;
  VETTORE2: string;
  V2DATA: string | null;
  V2ORA: string;
  TRCAUSALE: string;
  COLLI: string;
  SPEDIZIONE: string;
  PORTO: string;
  NOTE: string;
  SPESETR: number;
  SPESETRIVA: string;
  SPESETRCP: string;
  SPESETRPER: string;
  SPESEIM: number;
  SPESEIMIVA: string;
  SPESEIMCP: string;
  SPESEVA: number;
  SPESEVAIVA: string;
  SPESEVACP: string;
  ACCONTO: number;
  ABBUONO: number;
  TOTIMP: number;
  TOTDOC: number;
  SPESE: string;
  SPESEBOLLI: number;
  SPESEINCAS: number;
  SPESEINEFF: number;
  SPESEINDOC: number;
  SPESEINIVA: string;
  SPESEINCP: string;
  SPESEESENZ: number;
  CODCAUMAG: string;
  CODBANCA: string;
  PERCPROVV: number;
  IMPPROVV: number;
  TOTPROVV: number;
  PERCPROVV2: number;
  IMPPROVV2: number;
  TOTPROVV2: number;
  TOTIVA: number;
  ASPBENI: string;
  SCORPORO: boolean;
  TOTMERCE: number;
  TOTSCONTO: number;
  TOTNETTO: number;
  TOTESEN: number;
  IMPCOND: number;
  RITCOND: number;
  TIPOFATT: string;
  TRIANGOLAZ: boolean;
  NOMODIFICA: boolean;
  NOEVASIONE: boolean;
  COMMESSA: string;
  EUROCAMBIO: number;
  EXPORT_I: boolean;
  CB_BIC: string;
  CB_NAZIONE: string;
  CB_CIN_UE: string;
  CB_CIN_IT: string;
  ABICAB: string;
  CONTOCORR: string;
  CARICATORE: string;
  COMMITTENT: string;
  PROPRMERCE: string;
  LUOGOCAR: string;
  LUOGOSCAR: string;
  SDTALTRO: string;
  TIMESTAMP: string | null;
  USERNAME: string;
};

export type ArcaRiga = {
  ID: number;
  ID_TESTA: number;
  ESERCIZIO: string;
  TIPODOC: string;
  NUMERODOC: string;
  DATADOC: string | null;
  CODICECF: string;
  MAGPARTENZ: string;
  MAGARRIVO: string;
  AGENTE: string;
  AGENTE2: string;
  VALUTA: string;
  CAMBIO: number;
  CODICEARTI: string;
  NUMERORIGA: number;
  ESPLDISTIN: string;
  UNMISURA: string;
  QUANTITA: number;
  QUANTITARE: number;
  SCONTI: string;
  PREZZOUN: number;
  PREZZOTOT: number;
  ALIIVA: string;
  CONTOSCARI: string;
  OMIVA: boolean;
  OMMERCE: boolean;
  PROVV: string;
  PROVV2: string;
  DATACONSEG: string | null;
  DESCRIZION: string;
  TIPORIGAD: string;
  RESTOSCORP: number;
  RESTOSCUNI: number;
  CODCAUMAG: string;
  ZONA: string;
  SETTORE: string;
  GRUPPO: string;
  CLASSE: string;
  RIFFROMT: number;
  RIFFROMR: number;
  PREZZOTOTM: number;
  NOTE: string;
  COMMESSA: string;
  TIMESTAMP: string | null;
  USERNAME: string;
  FATT: number;
  LOTTO: string;
  MATRICOLA: string;
  EUROCAMBIO: number;
  U_PESON: number;
  U_PESOL: number;
  U_COLLI: number;
  U_GIA: number;
  U_MAGP: string;
  U_MAGA: string;
};

export type ArcaDestinazione = {
  CODICECF: string;
  CODICEDES: string;
  RAGIONESOC: string;
  SUPPRAGSOC: string;
  INDIRIZZO: string;
  CAP: string;
  LOCALITA: string;
  PROVINCIA: string;
  CODNAZIONE: string;
  AGENTE: string;
  AGENTE2: string;
  SETTORE: string;
  ZONA: string;
  VETTORE: string;
  TELEFONO: string;
  FAX: string;
  PERSONARIF: string;
  TIMESTAMP: string | null;
  USERNAME: string;
};

export type ArcaClientData = {
  codice: string;
  ragioneSociale: string;
  supplRagioneSociale?: string;
  indirizzo?: string;
  cap?: string;
  localita?: string;
  prov?: string;
  telefono?: string;
  fax?: string;
  email?: string;
  partitaIva?: string;
  codFiscale?: string;
  zona?: string;
  persDaContattare?: string;
  emailAmministraz?: string;
};

export type ArcaData = {
  testata: ArcaTestata;
  righe: ArcaRiga[];
  destinazione_diversa?: ArcaDestinazione | null;
};
