#!/bin/bash
# Script di debug per analizzare il problema WebSocket

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 ANALISI PROBLEMA WEBSOCKET - NESSUNA CONNESSIONE CLIENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 SINTOMI RILEVATI:"
echo "  ❌ Nessuna connessione WebSocket client nei log backend"
echo "  ❌ Admin panel mostra sempre status 'idle' (giallo)"
echo "  ✅ WebSocket server inizializzato correttamente"
echo "  ✅ Sync PDF periodica funziona"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔎 ANALISI CODEBASE COMPLETATA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📁 ARCHITETTURA FRONTEND:"
echo "  ├── AppRouter.tsx"
echo "  │   └── {auth.isAuthenticated && <WebSocketSync />}"
echo "  ├── WebSocketSync.tsx"
echo "  │   ├── useDraftSync() ──┐"
echo "  │   └── usePendingSync() ─┤"
echo "  └── hooks/                │"
echo "      ├── useDraftSync.ts ──┼── useWebSocket() [ISTANZA 1]"
echo "      └── usePendingSync.ts ─── useWebSocket() [ISTANZA 2]"
echo ""

echo "⚠️  PROBLEMA CRITICO IDENTIFICATO #1:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ MULTIPLE ISTANZE WEBSOCKET"
echo ""
echo "Ogni hook (useDraftSync, usePendingSync) chiama useWebSocket(),"
echo "creando una NUOVA istanza di WebSocket indipendente:"
echo ""
echo "  • useDraftSync() chiama useWebSocket() → crea ws://host/ws/realtime?token=xxx"
echo "  • usePendingSync() chiama useWebSocket() → crea ws://host/ws/realtime?token=xxx"
echo ""
echo "Risultato: 2 CONNESSIONI WEBSOCKET PARALLELE allo stesso endpoint!"
echo ""
echo "Questo è inefficiente e può causare:"
echo "  - Consumo doppio di risorse"
echo "  - Race conditions"
echo "  - Problemi di sincronizzazione"
echo "  - Possibile rifiuto da parte del server"
echo ""

echo "⚠️  PROBLEMA CRITICO IDENTIFICATO #2:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ DOPPIO WEBSOCKET SERVER NEL BACKEND"
echo ""
echo "Il backend ha DUE server WebSocket attivi contemporaneamente:"
echo ""
echo "  1. VECCHIO: /ws/sync (riga 97 in index.ts)"
echo "     export const wss = new WebSocketServer({ server, path: '/ws/sync' });"
echo ""
echo "  2. NUOVO: /ws/realtime (riga 6148 in index.ts)"
echo "     WebSocketServerService.getInstance().initialize(server);"
echo ""
echo "Il vecchio endpoint era stato DISABILITATO nel frontend (commit 2e2cf6c)"
echo "ma il server backend NON è stato rimosso!"
echo ""
echo "Questo può causare:"
echo "  - Interferenza tra i due server"
echo "  - Consumo inutile di risorse"
echo "  - Confusione nel debugging"
echo ""

echo "⚠️  PROBLEMA CRITICO IDENTIFICATO #3:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ TOKEN JWT NON VERIFICATO AL MOMENTO DEL MOUNT"
echo ""
echo "useWebSocket.ts controlla il token alla connessione (riga 163-168):"
echo ""
echo "  const token = getToken();"
echo "  if (!token) {"
echo "    console.warn('[WebSocket] No auth token, cannot connect');"
echo "    setState('disconnected');"
echo "    return;"
echo "  }"
echo ""
echo "Se il token non è disponibile quando il componente monta:"
echo "  → La connessione NON viene tentata"
echo "  → Nessun retry automatico se il token arriva dopo"
echo "  → Il componente rimane in stato 'disconnected' per sempre"
echo ""
echo "Possibili cause:"
echo "  - WebSocketSync monta prima che auth.token sia salvato in localStorage"
echo "  - Race condition tra login e mount del componente"
echo "  - Token scaduto e non rinnovato"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 RACCOMANDAZIONI DI FIX"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ FIX #1: SINGLETON WEBSOCKET (FRONTEND)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Creare UN'UNICA istanza WebSocket condivisa da tutti i componenti:"
echo ""
echo "Opzione A) WebSocket Context Provider (RACCOMANDATO)"
echo "  └── WebSocketProvider wrappa l'app e fornisce una singola connessione"
echo ""
echo "Opzione B) Singleton Service"
echo "  └── Convertire useWebSocket in un service globale con getInstance()"
echo ""
echo "Vantaggi:"
echo "  • Una sola connessione WebSocket"
echo "  • Gestione centralizzata dello stato"
echo "  • Più facile da debuggare"
echo "  • Meno consumo di risorse"
echo ""

echo "✅ FIX #2: RIMUOVERE VECCHIO WEBSOCKET SERVER (BACKEND)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Eliminare il vecchio WebSocket server /ws/sync dal backend:"
echo ""
echo "File: backend/src/index.ts"
echo "Riga 97: export const wss = new WebSocketServer({ server, path: '/ws/sync' });"
echo ""
echo "Azioni:"
echo "  1. Rimuovere l'inizializzazione del vecchio server"
echo "  2. Rimuovere tutti i riferimenti a wss (grep per trovare usi)"
echo "  3. Mantenere SOLO WebSocketServerService su /ws/realtime"
echo ""

echo "✅ FIX #3: GESTIRE TOKEN MANCANTE/SCADUTO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Aggiungere retry logic quando il token non è disponibile:"
echo ""
echo "  1. Aggiungere listener su localStorage per rilevare quando il token cambia"
echo "  2. Tentare reconnect quando un token valido diventa disponibile"
echo "  3. Verificare che WebSocketSync monti DOPO che auth.token è settato"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 PRIORITÀ DI INTERVENTO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔴 PRIORITÀ ALTA:"
echo "  1. FIX #1 - Implementare WebSocket Singleton/Context"
echo "     → Risolve il problema delle multiple connessioni"
echo ""
echo "🟡 PRIORITÀ MEDIA:"
echo "  2. FIX #2 - Rimuovere vecchio WebSocket server"
echo "     → Pulizia e prevenzione di conflitti futuri"
echo ""
echo "🟢 PRIORITÀ BASSA:"
echo "  3. FIX #3 - Gestire token mancante/scaduto"
echo "     → Potrebbe non essere necessario se Fix #1 risolve già"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 PIANO DI IMPLEMENTAZIONE DETTAGLIATO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "FASE 1: REFACTORING FRONTEND (Fix #1)"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Step 1.1: Creare WebSocketContext"
echo "  File: frontend/src/contexts/WebSocketContext.tsx"
echo "  - Creare Context con useWebSocket hook al suo interno"
echo "  - Esportare WebSocketProvider e useWebSocketContext"
echo ""
echo "Step 1.2: Wrappare l'app con WebSocketProvider"
echo "  File: frontend/src/AppRouter.tsx"
echo "  - Aggiungere <WebSocketProvider> intorno alle routes autenticate"
echo "  - Rimuovere <WebSocketSync /> (sostituito dal provider)"
echo ""
echo "Step 1.3: Aggiornare useDraftSync e usePendingSync"
echo "  Files:"
echo "    - frontend/src/hooks/useDraftSync.ts"
echo "    - frontend/src/hooks/usePendingSync.ts"
echo "  - Sostituire useWebSocket() con useWebSocketContext()"
echo ""

echo "FASE 2: CLEANUP BACKEND (Fix #2)"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Step 2.1: Rimuovere vecchio WebSocket server"
echo "  File: backend/src/index.ts"
echo "  - Commentare/rimuovere riga 97"
echo "  - Verificare con grep che non ci siano altri usi di 'wss'"
echo ""
echo "Step 2.2: Verificare dipendenze"
echo "  File: backend/src/price-endpoints.ts"
echo "  - Verificare se setWssInstance è ancora necessario"
echo "  - Se sì, migrare a WebSocketServerService"
echo ""

echo "FASE 3: TESTING"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Step 3.1: Test connessione WebSocket"
echo "  - Effettuare login"
echo "  - Verificare log browser console: '[WebSocket] Connected'"
echo "  - Verificare log backend: 'WebSocket client authenticated'"
echo ""
echo "Step 3.2: Test admin panel"
echo "  - Aprire pagina admin"
echo "  - Verificare status: 'healthy' (verde) invece di 'idle'"
echo "  - Verificare 'Connessioni Attive' > 0"
echo ""
echo "Step 3.3: Test sync real-time"
echo "  - Creare draft order"
echo "  - Verificare sync immediato"
echo "  - Verificare log WebSocket eventi"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 VUOI PROCEDERE CON L'IMPLEMENTAZIONE?"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Prossimi passi:"
echo "  1. Conferma il piano di fix"
echo "  2. Implemento il refactoring con WebSocketContext"
echo "  3. Rimuovo il vecchio WebSocket server"
echo "  4. Testiamo la connessione"
echo ""
