-- 043-drop-order-documents-columns.sql
-- DESTRUCTIVE: Drop old flat DDT/invoice/tracking columns from order_records.
-- Only run AFTER verifying migration 042 + new code work correctly in production.

BEGIN;

ALTER TABLE agents.order_records
  DROP COLUMN IF EXISTS ddt_number,
  DROP COLUMN IF EXISTS ddt_delivery_date,
  DROP COLUMN IF EXISTS ddt_id,
  DROP COLUMN IF EXISTS ddt_customer_account,
  DROP COLUMN IF EXISTS ddt_sales_name,
  DROP COLUMN IF EXISTS ddt_delivery_name,
  DROP COLUMN IF EXISTS delivery_terms,
  DROP COLUMN IF EXISTS delivery_method,
  DROP COLUMN IF EXISTS delivery_city,
  DROP COLUMN IF EXISTS attention_to,
  DROP COLUMN IF EXISTS ddt_delivery_address,
  DROP COLUMN IF EXISTS ddt_quantity,
  DROP COLUMN IF EXISTS ddt_customer_reference,
  DROP COLUMN IF EXISTS ddt_description,
  DROP COLUMN IF EXISTS tracking_number,
  DROP COLUMN IF EXISTS tracking_url,
  DROP COLUMN IF EXISTS tracking_courier,
  DROP COLUMN IF EXISTS delivery_completed_date,
  DROP COLUMN IF EXISTS tracking_status,
  DROP COLUMN IF EXISTS tracking_key_status_cd,
  DROP COLUMN IF EXISTS tracking_status_bar_cd,
  DROP COLUMN IF EXISTS tracking_estimated_delivery,
  DROP COLUMN IF EXISTS tracking_last_location,
  DROP COLUMN IF EXISTS tracking_last_event,
  DROP COLUMN IF EXISTS tracking_last_event_at,
  DROP COLUMN IF EXISTS tracking_last_synced_at,
  DROP COLUMN IF EXISTS tracking_sync_failures,
  DROP COLUMN IF EXISTS tracking_origin,
  DROP COLUMN IF EXISTS tracking_destination,
  DROP COLUMN IF EXISTS tracking_service_desc,
  DROP COLUMN IF EXISTS delivery_confirmed_at,
  DROP COLUMN IF EXISTS delivery_signed_by,
  DROP COLUMN IF EXISTS tracking_events,
  DROP COLUMN IF EXISTS tracking_delay_reason,
  DROP COLUMN IF EXISTS tracking_delivery_attempts,
  DROP COLUMN IF EXISTS tracking_attempted_delivery_at,
  DROP COLUMN IF EXISTS invoice_number,
  DROP COLUMN IF EXISTS invoice_date,
  DROP COLUMN IF EXISTS invoice_amount,
  DROP COLUMN IF EXISTS invoice_customer_account,
  DROP COLUMN IF EXISTS invoice_billing_name,
  DROP COLUMN IF EXISTS invoice_quantity,
  DROP COLUMN IF EXISTS invoice_remaining_amount,
  DROP COLUMN IF EXISTS invoice_tax_amount,
  DROP COLUMN IF EXISTS invoice_line_discount,
  DROP COLUMN IF EXISTS invoice_total_discount,
  DROP COLUMN IF EXISTS invoice_due_date,
  DROP COLUMN IF EXISTS invoice_payment_terms_id,
  DROP COLUMN IF EXISTS invoice_purchase_order,
  DROP COLUMN IF EXISTS invoice_closed,
  DROP COLUMN IF EXISTS invoice_days_past_due,
  DROP COLUMN IF EXISTS invoice_settled_amount,
  DROP COLUMN IF EXISTS invoice_last_payment_id,
  DROP COLUMN IF EXISTS invoice_last_settlement_date,
  DROP COLUMN IF EXISTS invoice_closed_date;

COMMIT;
