export interface Customer {
  customerProfile: string;
  internalId: string | null;
  name: string;
  vatNumber: string | null;
  fiscalCode: string | null;
  sdi: string | null;
  pec: string | null;
  email: string | null;
  phone: string | null;
  mobile: string | null;
  url: string | null;
  attentionTo: string | null;
  street: string | null;
  logisticsAddress: string | null;
  postalCode: string | null;
  city: string | null;
  customerType: string | null;
  type: string | null;
  deliveryTerms: string | null;
  description: string | null;
  lastOrderDate: string | null;
  actualOrderCount: number;
  actualSales: number;
  previousOrderCount1: number;
  previousSales1: number;
  previousOrderCount2: number;
  previousSales2: number;
  externalAccountNumber: string | null;
  ourAccountNumber: string | null;
  hash: string;
  lastSync: number;
  createdAt: number;
  updatedAt: number;
  botStatus?: "pending" | "placed" | "snapshot" | "failed" | null;
  photoUrl?: string | null;
  vatValidatedAt: string | null;
  // Extended fields from migration 037
  sector?: string | null;
  priceGroup?: string | null;
  lineDiscount?: string | null;
  paymentTerms?: string | null;
  notes?: string | null;
  nameAlias?: string | null;
  county?: string | null;
  state?: string | null;
  country?: string | null;
}
