export interface Customer {
  erpId: string;
  accountNum: string | null;
  name: string;
  vatNumber: string | null;
  fiscalCode: string | null;
  sdi: string | null;
  pec: string | null;
  email: string | null;
  phone: string | null;
  mobile: string | null;
  url: string | null;
  attentionTo: string | null;
  street: string | null;
  logisticsAddress: string | null;
  postalCode: string | null;
  city: string | null;
  customerType: string | null;
  type: string | null;
  deliveryTerms: string | null;
  description: string | null;
  lastOrderDate: string | null;
  actualOrderCount: number;
  actualSales: number;
  previousOrderCount1: number;
  previousSales1: number;
  previousOrderCount2: number;
  previousSales2: number;
  externalAccountNumber: string | null;
  ourAccountNumber: string | null;
  hash: string;
  lastSync: number;
  createdAt: number;
  updatedAt: number;
  botStatus?: "pending" | "placed" | "snapshot" | "failed" | null;
  photoUrl?: string | null;
  vatValidatedAt: string | null;
  vatInvalid: boolean;
  vatLastBgCheckAt: string | null;
  // Extended fields from migration 037
  sector?: string | null;
  priceGroup?: string | null;
  lineDiscount?: string | null;
  paymentTerms?: string | null;
  notes?: string | null;
  nameAlias?: string | null;
  county?: string | null;
  state?: string | null;
  country?: string | null;
  agentNotes?: string | null;
  erpDetailReadAt: string | null;
  // Migration 091 — post-update ERP Germania 2026-05-10
  fnomceo?: string | null;
  exclusivityDaysRemaining?: number | null;
  exclusivityEndDate?: string | null;
  exclusivityStartDate?: string | null;
  exclusivitySalesForecast?: number | null;
  exclusivitySalesActual?: number | null;
  crmRefId?: string | null;
  crmOldRefId?: string | null;
  crmAccountCommercial?: string | null;
  crmContactType?: string | null;
  erpCreatedAt?: string | null;
  erpCreatedBy?: string | null;
  erpModifiedAt?: string | null;
  erpModifiedBy?: string | null;
  geoAddress?: string | null;
  geoLatitude?: number | null;
  geoLongitude?: number | null;
  altreInfoSyncedAt?: string | null;
  blocked_status?: string | null;
  blockedStatus?: string | null;
  contactWritePendingAt?: string | null;
  hidden?: boolean;
}
